### ISSUE TITLE
Showcase page not working

### ISSUE THREAD

**Issue by jgomer2001** [stephanrauh/AngularFaces#82] opened 2017-12-26 14:12 UTC
Hi Stephan,
Not the best way to contact you, but I am lazy... 
The page https://www.angularfaces.net/ is throwing

```
Facelet /index_en.xhtml not found at: file:/var/www/virtual/angularfaces.net/apache-tomcat-8.0.14/webapps/ROOT/index_en.xhtml

viewId=/index.xhtml
location=/var/www/virtual/angularfaces.net/apache-tomcat-8.0.14/webapps/ROOT/index.xhtml
phaseId=RENDER_RESPONSE(6)

Caused by:
java.io.FileNotFoundException - Facelet /index_en.xhtml not found at: file:/var/www/virtual/angularfaces.net/apache-tomcat-8.0.14/webapps/ROOT/index_en.xhtml
at org.apache.myfaces.view.facelets.impl.DefaultFaceletFactory._createFacelet(DefaultFaceletFactory.java:387)
```

Happy new year!

**Comment by stephanrauh** [comment] 2017-12-26 16:00
Hi Jose,

actually, it's the preferred way to contact me :). Of course, you can also find my e-mail address after a minute of Googling, but since you've reported a bug, the bug tracker is the way to go.

I've tried to reproduce your bug. If I get it right, it occurs immediately on the front page? This page works fine for me, in each of the three languages. The other pages also seem to work. Maybe it was a short glitch, possibly caused by an update or maintenance of my server provider?

Best regards and Happy New Year
Stephan

**Comment by jgomer2001** [comment] 2017-12-27 12:15
HI step,
This is what I am seeing in this moment:
![angfaces_error](https://user-images.githubusercontent.com/5444180/34381296-aa543680-ead5-11e7-889d-d5473859cfeb.png)


Regards.

**Comment by stephanrauh** [comment] 2022-11-10 17:28
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.

**Closed as completed by stephanrauh** 2022-11-10 17:28 UTC
Labels: bug, documentation
