### ISSUE TITLE
run AngularFaces-2.0-examples on eclipse

### ISSUE THREAD

**Issue by KuangLan** [stephanrauh/AngularFaces#63] opened 2015-12-02 10:21 UTC
SEVERE: Servlet.service() for servlet [Faces Servlet] in context with path [/AngularFaces-2.0-examples] threw exception [null] with root cause
java.lang.NullPointerException
    at de.beyondjava.angularFaces.components.puiModelSync.PuiModelSync.getFacesModel(PuiModelSync.java:204)

**Comment by stephanrauh** [comment] 2015-12-02 21:11
That's the example application containing the car dealer demo, I suppose? Well, it works fine on my machine. What did you do exactly? Does the application crash at the first screen, or does it crash when you perform a specific action?

**Comment by KuangLan** [comment] 2015-12-03 04:07
Yes. the car dealer demo crash and log reports "NullPointerException"

**Comment by stephanrauh** [comment] 2015-12-03 20:11
I still need your help to reproduce and solve the bug. Can you tell me something about your runtime environment? Do you deploy to a Tomcat? Which libraries do you use?

**Comment by KuangLan** [comment] 2015-12-04 06:49
Hi Stephan,
  I thought I find the reason:
trace the exception thrown from object
de.beyondjava.angularFaces.components.puiModelSync
check the code and
   find the JSONUtilities has not initilized the JSON library.
when i copy the Jackson library from  Maven directory to  the workspace's
WEB-INF/lib,  everything is ok.

Thanks a lot, Guru of JSF.
you can close this issue now.

Best Regards
Alex


On Fri, Dec 4, 2015 at 4:11 AM, Stephan Rauh <notifications@github.com>
wrote:

> I still need your help to reproduce and solve the bug. Can you tell me
> something about your runtime environment? Do you deploy to a Tomcat? Which
> libraries do you use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephanrauh/AngularFaces/issues/63#issuecomment-161769485>
> .
>



-- 
Best Regards
*Kuang Lan*

**Comment by KuangLan** [comment] 2015-12-04 07:03
Sorry it is not a bug!
 trace the exception thrown from object  de.beyondjava.angularFaces.components.puiModelSync
check the code and
  trace the exception thrown from object  de.beyondjava.angularFaces.components.puiModelSync
check the code and
   find the JSONUtilities has not initilized the JSON library.
when i copy the Jackson library from  Maven directory to  the workspace's WEB-INF/lib,  everything is ok.

**Comment by stephanrauh** [comment] 2015-12-04 08:11
Good to know you've solved the problem. I guess I should add this to the documentation, don't you think?

**Comment by KuangLan** [comment] 2015-12-04 09:18
Guru,   you go ahead just

**Comment by stephanrauh** [comment] 2022-11-10 17:30
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.

**Closed by stephanrauh** 2022-11-10 17:30 UTC
Labels: bug, documentation
